services:

  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    networks:
      - strapi
    volumes:
      - /home/fedora/Bureau/S6/Projet/OPSCI2024/postgres:/var/lib/postgresql/data

  strapi:
    container_name: strapi
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      PORT: 1337
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
    volumes:
      - ./backend/config:/home/fedora/Bureau/S6/Projet/OPSCI2024/backend/config
      - ./backend/src:/home/fedora/Bureau/S6/Projet/OPSCI2024/backend/src
      - ./backend/package.json:/home/fedora/Bureau/S6/Projet/OPSCI2024/backend/package.json
      - ./backend/yarn.lock:/home/fedora/Bureau/S6/Projet/OPSCI2024/backend/yarn.lock
      - ./backend/.env:/home/fedora/Bureau/S6/Projet/OPSCI2024/backend/.env
      - ./backend/public/uploads:/home/fedora/Bureau/S6/Projet/OPSCI2024/backend/public/uploads

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    expose:
      - '2181'
    networks:
      - strapi

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
       KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093,OUTSIDE://kafka:9092,
       KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
       KAFKA_DELETE_TOPIC_ENABLE: 'true'
       KAFKA_ADVERTISED_PORT: 9092
       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       KAFKAJS_NO_PARTITIONER_WARNING: '1'
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
       KAFKA_NO_LISTENER_AUTHENTICATION_PLAINTEXT: 'true'
       KAFKA_NO_LISTENER_AUTHENTICATION_SSL: 'true'
       KAFKA_BROKER_ID: 1
       KAFKA_LOG_RETENTION_HOURS: 168
       KAFKA_LOG_RETENTION_BYTES: 1073741824
       KAFKA_LOG_DIRS: /kafka/logs
       KAFKA_ADVERTISED_HOST_NAME: kafka
    expose:
      - '9092'
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - strapi

volumes:
  postgres:

networks:
  strapi:
    name: Strapi
    driver: bridge
